# analysis_options.yaml
# Configuracion optimizada segun Framework de Madurez Flutter de Pragma
# Fuente: mobile-flutter-rules.md (MCP Pragma Server)
# Fecha: 2025-12-15

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Pragma: "No usar print para depurar la aplicacion"
    avoid_print: error
    # Codigo muerto como warning
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    # ============================================
    # MANTENIBILIDAD - Convenciones de Codigo
    # Pragma: "Nombres claros, descriptivos y consistentes"
    # Pragma: "Condicionales y bucles envueltos por { }"
    # ============================================
    curly_braces_in_flow_control_structures: true
    file_names: true
    non_constant_identifier_names: true
    camel_case_types: true
    constant_identifier_names: true
    library_names: true
    library_prefixes: true

    # ============================================
    # MANTENIBILIDAD - Codigo Limpio
    # Pragma: "Eliminar codigo muerto, innecesario o sin uso"
    # Pragma: "Escribe codigo legible, sencillo y autodocumentado"
    # ============================================
    always_declare_return_types: true
    type_annotate_public_apis: true
    avoid_redundant_argument_values: true
    unnecessary_this: true
    unnecessary_new: true
    unnecessary_const: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true

    # ============================================
    # MAINTAINABILITY - Immutability
    # Pragma: "Data models and states should be immutable"
    # Pragma: "All properties should be final"
    # ============================================
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_late: true

    # ============================================
    # TRACEABILITY - Error handling
    # Pragma: "Do not use print for debugging"
    # Pragma: "Avoid ignoring try/catch exceptions"
    # Pragma: "Validate null values using null-aware operators"
    # ============================================
    avoid_print: true
    empty_catches: true
    avoid_catching_errors: true
    use_rethrow_when_possible: true
    avoid_null_checks_in_equality_operators: true
    null_check_on_nullable_type_parameter: true
    null_closures: true

    # ============================================
    # PERFORMANCE - Widgets
    # Pragma: "Use const whenever possible"
    # Pragma: "Do not use Container for empty spacing"
    # Pragma: "Always release unused resources"
    # ============================================
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    avoid_unnecessary_containers: true
    cancel_subscriptions: true
    close_sinks: true
    use_key_in_widget_constructors: true

    # ============================================
    # ESTILO Y FORMATO
    # Pragma: "Sigue las convenciones de estilo del lenguaje"
    # ============================================
    prefer_single_quotes: true
    slash_for_doc_comments: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true

    # Preferencias de colecciones y strings
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_contains: true
    prefer_collection_literals: true
    prefer_spread_collections: true
    prefer_iterable_whereType: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_inlined_adds: true

    # Preferencias de null safety
    prefer_null_aware_operators: true
    prefer_if_null_operators: true
    prefer_conditional_assignment: true

    # Preferencias de sintaxis
    prefer_adjacent_string_concatenation: true
    prefer_interpolation_to_compose_strings: true
    prefer_function_declarations_over_variables: true
    prefer_initializing_formals: true
    prefer_is_not_operator: true
    prefer_typing_uninitialized_variables: true

    # Control de flujo y estructura
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_on_closure_parameters: true
    await_only_futures: true
    control_flow_in_finally: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    implementation_imports: true
    no_duplicate_case_values: true
    overridden_fields: true
    provide_deprecation_message: true
    recursive_getters: true
    type_init_formals: true
    unawaited_futures: true
    unrelated_type_equality_checks: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    valid_regexps: true
    void_checks: true

    # ============================================
    # REGLAS DESHABILITADAS INTENCIONALMENTE
    # ============================================
    # Muy estrictas para aplicaciones (mejor para paquetes publicos)
    public_member_api_docs: false
    # Preferencia personal del equipo
    lines_longer_than_80_chars: false
    # Dart infiere bien los tipos
    always_specify_types: false

# Documentacion: https://dart.dev/guides/language/analysis-options
# Reglas disponibles: https://dart.dev/lints
